
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, filedialog

import pandas as pd
import csv

dict_arr = []


def load_csv(fp: str, col_one: int, col_two: int):
  with open(fp, mode='r', encoding="utf8") as inp:
    reader = csv.reader(inp)
    dict_arr.append({rows[col_one]: rows[col_two] for rows in reader})


def update():
    dict_arr[1].update(dict_arr[0])
    data = dict_arr[1].items()
    pd.DataFrame(data=data).to_csv("tes1et.csv", index=False, header=None)

def processButton(old, new):
    old = f"{old.lower().split('.')[0]}.csv"
    new = f"{new.lower().split('.')[0]}.csv"
    print(old, new)

    load_csv(new, 26, 30)
    load_csv(old, 2, 14)

    update()


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.title("Vim & Co. Website Stock Updater")
window.geometry("500x600")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 600,
    width = 500,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    88.0,
    187.0,
    anchor="nw",
    text="Enter the name of the old website export document",
    fill="#000000",
    font=("Inter", 13 * -1)
)

def select_file():
    filetypes = [('CSV', '*.csv')]


    filename = filedialog.askopenfilename(
        title='select afile',
        initialdir='/',
        filetypes=filetypes
    )

    print(filename)
    return filename


open_button = Button(
    text='hello',
    command=select_file,
    borderwidth=0,
    highlightthickness=0,
    relief="flat"
)

open_button.place(
    x=40.0,
    y=278.0,
    width=420.0,
    height=57.0
)

# entry_image_1 = PhotoImage(
#     file=relative_to_assets("entry_1.png"))
# entry_bg_1 = canvas.create_image(
#     250.0,
#     245.5,
#     image=entry_image_1
# )
# entry_1 = Entry(
#     bd=0,
#     bg="#F7F7F7",
#     highlightthickness=0
# )
# entry_1.place(
#     x=54.0,
#     y=217.0,
#     width=392.0,
#     height=55.0
# )

# canvas.create_text(
#     52.0,
#     307.0,
#     anchor="nw",
#     text="Enter the name of the inventory management export document",
#     fill="#000000",
#     font=("Inter", 13 * -1)
# )

# entry_image_2 = PhotoImage(
#     file=relative_to_assets("entry_2.png"))
# entry_bg_2 = canvas.create_image(
#     250.0,
#     365.5,
#     image=entry_image_2
# )
# entry_2 = Entry(
#     bd=0,
#     bg="#F7F7F7",
#     highlightthickness=0
# )
# entry_2.place(
#     x=54.0,
#     y=337.0,
#     width=392.0,
#     height=55.0
# )

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda:processButton(entry_1.get(), entry_2.get()),
    relief="flat"
)
button_1.place(
    x=40.0,
    y=478.0,
    width=420.0,
    height=57.0
)

canvas.create_text(
    75.0,
    65.0,
    anchor="nw",
    text="Website Stock Updater",
    fill="#000000",
    font=("Inter Regular", 32 * -1)
)
window.resizable(False, False)
window.mainloop()
